# 多说分享评论用到
url: "http://bluebiu.com"
#url: "http://bluebiulocal.com:4000/"
share_img: "img/wx_share_default.jpg"

# Index
title: Biu^Biu's Blog
hometitle: "Biu^Biu"
header-img: "img/autumn_color.jpg"
description: "美好，美好。"
keyword: "biubiu, @biubiu, biu.lao, Biu^Biu's blog, bluebiu github, biubiu的博客"
# baseurl: ""

# About/contact
owner:
  name: "biu.lao"
  email: 38339086@qq.com
  biography: "坚持，坚持。美好，美好。"

# nav.html
navs:
  -
    title: "Home"
    url: "/"
  -
    title: "Timeline"
    url: "/documents.html"
  -
    title: "Categories"
    url: "/categories.html"
  -
    title: "Tags"
    url: "/tags.html"
  -
    title: "About"
    url: "/about.html"

# foot.html
socialname:
  douban: ""
  twitter: ""
  facebook: ""
  github: "bluebiu"
  weibo: "bluelooord"
  zhihu: "bluebiu"

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
  #use_coderay: true
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # smart_quotes: ["lsquo","rsquo","ldquo","rdquo"]
  # enable_coderay: false

  # coderay:
  #   coderay_wrap: div
  #   coderay_line_numbers: inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: style

highlighter: rouge

# rouge:
#   formatter:
#     css_class: 'highlight'
#     line_numbers: true


gems: ["jekyll-paginate"]
permalink: none
# permalink默认是date, 还有pretty. none是/:categories/:title.html
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
encoding: UTF-8

# Defaults for posts
defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts"
    values:
      layout: "post"
      author: "biu.lao"
#      header-img: "img/ship_in_hand.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : bluebiu

