# 多说分享评论用到
url: "http://bluebiu.com"
#url: "http://bluebiulocal.com:4000"
share_img: "/img/wx_share_default.jpg"

# Index
title: "Biu^Biu's Blog"
hometitle: "Biu^Biu"
header-img: "/img/autumn_color.jpg"
description: "美好，美好。"
keyword: "biubiu, @biubiu, Biu^Biu's blog, bluebiu github, biubiu的博客"
# baseurl: ""

# About/contact
owner:
  name: "biubiu"
  email: 38339086@qq.com
  biography: "坚持，坚持。美好，美好。"

# nav.html
navs:
  -
    title: "Home"
    url: "http://www.bluebiu.com"
  -
    title: "Timeline"
    url: "/documents.html"
  -
    title: "Categories"
    url: "/categories.html"
  -
    title: "Tags"
    url: "/tags.html"
  -
    title: "About"
    url: "/about.html"

# foot.html
socialname:
  douban: ""
  twitter: ""
  facebook: ""
  github: "bluebiu"
  weibo: "bluelooord"
  zhihu: "bluebiu"

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
  # toc目录结构默认「1..6」
  toc_levels: 1..5
highlighter: rouge

# rouge:
#   formatter:
#     css_class: 'highlight'
#     line_numbers: true


gems: ["jekyll-paginate"]
permalink: none
# permalink默认是date, 还有pretty. none是/:categories/:title.html
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
encoding: UTF-8

# Defaults for posts
defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts"
    values:
      layout: "post"
      author: "biubiu"
#      header-img: "img/ship_in_hand.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : "duoshuo"
  duoshuo :
    short_name : "bluebiu"


# # 服务器选项
# detach: false
# port: "4000"
# host: "127.0.0.1"
# baseurl: "" # does not include hostname

# Static url
# img_url末尾不加「/」，图片的值都填的「/img」开头，方便调试 -160218
img_url: "http://static.bluebiu.com"
source_url: "http://static.bluebiu.com"

# Static version
css_version: "1457180575" # 2016年 3月 5日 星期六 20时23分06秒 CST
js_version: "1455364935" # 2016年 2月13日 星期六 20时02分42秒 CST
img_version: "1455364935" # 2016年 2月13日 星期六 20时02分42秒 CST
